[package]
name = "download_manager"
version = "0.3.1"
edition = "2018"
authors = ["thin-edge.io team <info@thin-edge.io>"]
license = "Apache-2.0"
description = "download_manager"


[dependencies]
reqwest = "0.11"
serde = "1.0"
tedge_utils = { path = "../../common/tedge_utils" }
tempfile = "3.2"
thiserror = "1.0"

[dev-dependencies]
regex = "1.5"
tokio = "1.9"
tokio-test = "0.4"
